### ISSUE TITLE
can only throw objects

### ISSUE THREAD

**Issue by dbu** [php-http/client-common#109] opened 2018-09-23 06:55 UTC
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 1.8.0

#### Actual Behavior

Error: Can only throw objects
/home/travis/build/php-http/HttplugBundle/vendor/php-http/client-common/src/Deferred.php:129
/home/travis/build/php-http/HttplugBundle/vendor/php-http/client-common/src/PluginClient.php:87
/home/travis/build/php-http/HttplugBundle/Tests/Functional/ProfilingTest.php:96

**Comment by Nyholm** [comment] 2018-09-23 10:31
I think, the issue is that `$this->state` is not updated after we execute the callback. 
https://github.com/php-http/client-common/blob/1.8.0/src/Deferred.php#L118

**Comment by mxr576** [comment] 2018-09-25 09:10
@joelwurtz @Nyholm any ETA for a fix for this? If someone installs our module with the latest version of the php-http/client-common lots of things gets broken and I do not want to create a new release just to blacklist php-http/client-common:>=1.8.0. Couldn't you rollback the related changes in a new 1.8.1 release until you can figure out how to address this problem properly?

Btw wasn't this change a BC breaking change so it should have been introduced in 2.x.y?

**Comment by joelwurtz** [comment] 2018-09-25 12:54
There is a fix in #110 if you have time to test it would be nice (but it fixes this bug on my end)

**Comment by mxr576** [comment] 2018-09-25 14:08
@joelwurtz Please see my comment in #110.

**Comment by Jean85** [comment] 2018-09-26 20:47
This is currently breaking the build in the incoming 2.0 release of the Sentry client: https://travis-ci.org/getsentry/sentry-php/jobs/433720358

#110 does not currently fix the issue. I'll have to add a conflict to `^1.8.0` until this is fixed.

**Comment by pascal-hofmann** [comment] 2018-10-02 14:35
I ran into this issue too. Is there a reason for not pulling back the 1.8 release? I guess this will cause harm for more people…

**Comment by mxr576** [comment] 2018-10-08 05:56
Seriously guys, just rollback these changes... since two weeks all depending libs/projects are that uses the retry plugin with a synchronous client are broken. If you do not have time to find the proper fix for this is fine, this is open source, rolling back the problematic changes since 1.7.0 should not be that complicated/time consuming.

**Comment by Jean85** [comment] 2018-10-08 20:42
#111 reverts everything but it's still pending...

**Closed** 2018-10-09 06:43 UTC

**Comment by dbu** [comment] 2018-10-09 06:47
i released 1.8.1 with the revert now.

**Comment by dbu** [comment] 2018-10-09 06:51
created #112 to document the problem but i don't plan to work on this.
